import Link from "next/link";

export default function TermsPage() {
  return (
    <div className="flex flex-col min-h-screen">
      <header className="border-b">
        <div className="container mx-auto py-4 px-4 md:px-6">
          <Link href="/" className="flex items-center space-x-2">
            <div className="w-8 h-8 rounded-full bg-teal-500 flex items-center justify-center">
              <span className="text-white font-semibold">AI</span>
            </div>
            <span className="font-semibold text-lg">MedIntake</span>
          </Link>
        </div>
      </header>

      <main className="flex-1 container mx-auto py-12 px-4 md:px-6">
        <div className="max-w-3xl mx-auto">
          <h1 className="text-3xl font-bold mb-6">Terms of Service</h1>
          
          <div className="prose prose-lg">
            <p className="text-sm text-gray-500 mb-8">
              <strong>Last Updated:</strong> May 23, 2025
            </p>

            <p className="mb-4">
              Welcome to the AI Medical Intake Proof-of-Concept (PoC) application. This application is an experimental demonstration of AI capabilities in processing spoken medical intake.
            </p>

            <p className="font-bold mb-6">
              PLEASE READ THESE TERMS CAREFULLY BEFORE USING THIS APPLICATION.
            </p>

            <h2 className="text-xl font-semibold mt-8 mb-4">1. Nature of the Service</h2>
            <p className="mb-4">
              This AI Medical Intake PoC application ("the App") is an <strong>experimental, demonstration tool only</strong>. It uses artificial intelligence to process spoken input regarding medical symptoms or conditions and provides synthesized audio summaries or responses.
            </p>
            
            <h2 className="text-xl font-semibold mt-8 mb-4">2. NO MEDICAL ADVICE, DIAGNOSIS, OR TREATMENT</h2>
            <p className="mb-4">
              <strong>THIS APP DOES NOT PROVIDE MEDICAL ADVICE, DIAGNOSIS, OR TREATMENT.</strong> The information and responses generated by this App are for informational and demonstration purposes only and should <strong>NOT</strong> be considered as professional medical advice. You <strong>MUST</strong> consult with a qualified healthcare professional for any medical concerns, diagnoses, or treatment decisions. Reliance on any information provided by this App is solely at your own risk.
            </p>
            
            <h2 className="text-xl font-semibold mt-8 mb-4">3. Disclaimer of Warranties</h2>
            <p className="mb-4">
              THE APP IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS, WITHOUT ANY WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED. THIS INCLUDES, BUT IS NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, AND ACCURACY. We do not warrant that the App will be uninterrupted, error-free, secure, or free from viruses or other harmful components. We make no guarantees regarding the accuracy, completeness, or reliability of any information or responses provided by the App.
            </p>
            
            <h2 className="text-xl font-semibold mt-8 mb-4">4. Limitation of Liability</h2>
            <p className="mb-4">
              TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL THE DEVELOPER(S) OF THIS APP BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS OR REVENUES, WHETHER INCURRED DIRECTLY OR INDIRECTLY, OR ANY LOSS OF DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES, RESULTING FROM (A) YOUR ACCESS TO OR USE OF OR INABILITY TO ACCESS OR USE THE APP; (B) ANY CONDUCT OR CONTENT OF ANY THIRD PARTY ON THE APP; OR (C) UNAUTHORIZED ACCESS, USE, OR ALTERATION OF YOUR TRANSMISSIONS OR CONTENT. THIS LIMITATION OF LIABILITY APPLIES TO ANY CLAIMS, WHETHER BASED ON WARRANTY, CONTRACT, TORT, OR ANY OTHER LEGAL THEORY, AND WHETHER OR NOT THE DEVELOPER HAS BEEN INFORMED OF THE POSSIBILITY OF SUCH DAMAGE.
            </p>
            
            <h2 className="text-xl font-semibold mt-8 mb-4">5. User Responsibilities</h2>
            <ul className="list-disc pl-6 mb-4">
              <li className="mb-2">You are solely responsible for the accuracy of the audio input you provide.</li>
              <li className="mb-2">You understand that the App is experimental and may produce inaccurate, incomplete, or inappropriate responses.</li>
              <li className="mb-2">You agree not to use the App for any unlawful purpose or in any way that could harm the App or its users.</li>
            </ul>
            
            <h2 className="text-xl font-semibold mt-8 mb-4">6. Data Usage</h2>
            <p className="mb-4">
              Your use of this App is subject to our Privacy Policy, which explains how we collect, use, and process your data. By using this App, you consent to our data practices as described in the Privacy Policy.
            </p>
            
            <h2 className="text-xl font-semibold mt-8 mb-4">7. Changes to Terms</h2>
            <p className="mb-4">
              We reserve the right to modify these Terms of Service at any time. Your continued use of the App after any such changes constitutes your acceptance of the new Terms.
            </p>
            
            <h2 className="text-xl font-semibold mt-8 mb-4">8. Governing Law</h2>
            <p className="mb-4">
              These Terms shall be governed and construed in accordance with the laws of the State of Minnesota, United States, without regard to its conflict of law provisions.
            </p>
            
            <h2 className="text-xl font-semibold mt-8 mb-4">9. Contact Information</h2>
            <p className="mb-4">
              This is a PoC; direct support is not provided.
            </p>
          </div>
        </div>
      </main>

      <footer className="bg-gray-100 py-8">
        <div className="container mx-auto px-4 md:px-6">
          <div className="flex flex-col md:flex-row justify-between items-center">
            <div className="flex items-center space-x-2 mb-4 md:mb-0">
              <div className="w-6 h-6 rounded-full bg-teal-500 flex items-center justify-center">
                <span className="text-white font-semibold text-xs">AI</span>
              </div>
              <span className="font-semibold">MedIntake</span>
            </div>
            <div className="text-sm text-gray-500">Jake Moroshek | BuildAI © {new Date().getFullYear()}</div>
          </div>
        </div>
      </footer>
    </div>
  );
}
